# Generated by Django 5.0 on 2024-05-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
        ("users", "0002_alter_userprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.userprofile"
            ),
        ),
    ]
