# Generated by Django 5.0 on 2024-05-04 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_blogs_publisher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="description",
        ),
    ]
